---
title: "Research question 1"
author: "by: Electra"
bibliography: references.bib
---  

```{r, eval=F, echo=FALSE}
#install.packages("rgl")
```

```{r, install remotely, globalsettings, echo=FALSE, warning=FALSE, results='hide', eval=FALSE}
#install.packages("remotes")
#remotes::install_github("rlesur/klippy")
``` 

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()

colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

----  

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

----
  
This is just an example page of your `r colorize("lab journal", "red")`.
You can journal the assignments of the first day here.
  

----

# research question

*"To what extend the gender composition of Faculty of Science's board can influence the gender inequality within the facutly?"*  

"Science studies are considered by society as suitable only for males. Female researcher's according to the literature are very few and it seems that men tend to collaborate with fellow male researches excluding women from their Social network. Thus, is much harder for women to create a powerful social connections that may lead to career advancement. This research focuses on how the gender composition of the board can have an impact on gender inequality within and between the departments. To examine that this research examines the collaboration within the departments and with Faculty's board. Additionally, concentrates to the power dynamics. Does gender play any role in who the researches select to work with?"
----




